//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekhaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullancıBakiye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullancıBakiye()
        {
            this.Kullanıcı = new HashSet<Kullanıcı>();
        }
    
        public int KullancıBakiyeID { get; set; }
        public Nullable<int> kBakiye { get; set; }
        public Nullable<System.DateTime> kBakiyeYüklemeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanıcı> Kullanıcı { get; set; }
    }
}
