//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekhaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int KullanıcıID { get; set; }
        public string kAd { get; set; }
        public string kSoyad { get; set; }
        public string kTc { get; set; }
        public string kDogumYıl { get; set; }
        public Nullable<bool> kDurum { get; set; }
        public Nullable<int> kYetkiID { get; set; }
        public Nullable<int> KullanıcıBakiye { get; set; }
        public string kSifre { get; set; }
    
        public virtual KullancıBakiye KullancıBakiye { get; set; }
        public virtual KullanıcıYetki KullanıcıYetki { get; set; }
    }
}
