//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekhaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonleID { get; set; }
        public string personelAD { get; set; }
        public string PersonleSoyad { get; set; }
        public string PersonelGmail { get; set; }
        public string PersonelSifre { get; set; }
        public Nullable<int> PersonelYetkiID { get; set; }
        public string PersonelCinsiyet { get; set; }
        public Nullable<int> personelDogumYıl { get; set; }
        public string PersonelTCNo { get; set; }
    
        public virtual PersonelYetki PersonelYetki { get; set; }
    }
}
