//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekhaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yemek()
        {
            this.HaftalıkYemek = new HashSet<HaftalıkYemek>();
        }
    
        public int YemekID { get; set; }
        public string Yemekisim { get; set; }
        public Nullable<int> YemekKalori { get; set; }
        public Nullable<int> Yemekfiyat { get; set; }
        public Nullable<int> yemekMiktar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaftalıkYemek> HaftalıkYemek { get; set; }
    }
}
