//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekhaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ögrenciBakiye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ögrenciBakiye()
        {
            this.Ögrenci = new HashSet<Ögrenci>();
        }
    
        public int ögrenciBakiyeID { get; set; }
        public Nullable<short> ögrenciBakiye1 { get; set; }
        public Nullable<System.DateTime> ögrenciBakiyeYüklemeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ögrenci> Ögrenci { get; set; }
    }
}
